ALTER TABLE tenant_groups
  ADD COLUMN IF NOT EXISTS additional_fields jsonb NOT NULL DEFAULT '[]'::jsonb;

CREATE TABLE IF NOT EXISTS tenant_group_person_fields (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  tenant_group bigint NOT NULL REFERENCES tenant_groups(id) ON DELETE CASCADE,
  person_key text NOT NULL CHECK (person_key LIKE 'global:%' OR person_key LIKE 'app:%'),
  field_id text NOT NULL,
  value jsonb,
  UNIQUE (tenant_group, person_key, field_id)
);

CREATE INDEX IF NOT EXISTS idx_tenant_group_person_fields_person
  ON tenant_group_person_fields(tenant_group, person_key);

ALTER TABLE tenant_group_person_fields ENABLE ROW LEVEL SECURITY;

CREATE POLICY "users_select_tenant_group_person_fields"
  ON tenant_group_person_fields FOR SELECT
  USING (
    tenant_group IN (
      SELECT tgt.tenant_group
      FROM tenant_group_tenants tgt
      JOIN "tenantUsers" tu ON tu."tenantId" = tgt.tenant_id
      WHERE tu."userId" = auth.uid()::text
    )
  );

CREATE POLICY "admins_manage_tenant_group_person_fields"
  ON tenant_group_person_fields FOR ALL
  USING (
    tenant_group IN (
      SELECT tgt.tenant_group
      FROM tenant_group_tenants tgt
      JOIN "tenantUsers" tu ON tu."tenantId" = tgt.tenant_id
      WHERE tu."userId" = auth.uid()::text AND tu.role = 1
    )
  )
  WITH CHECK (
    tenant_group IN (
      SELECT tgt.tenant_group
      FROM tenant_group_tenants tgt
      JOIN "tenantUsers" tu ON tu."tenantId" = tgt.tenant_id
      WHERE tu."userId" = auth.uid()::text AND tu.role = 1
    )
  );

CREATE POLICY "users_manage_own_tenant_group_person_fields"
  ON tenant_group_person_fields FOR ALL
  USING (
    tenant_group IN (
      SELECT tgt.tenant_group
      FROM tenant_group_tenants tgt
      JOIN "tenantUsers" tu ON tu."tenantId" = tgt.tenant_id
      WHERE tu."userId" = auth.uid()::text
    )
    AND (
      person_key = 'app:' || auth.uid()::text
      OR person_key IN (
        SELECT 'global:' || p.global_person_id::text
        FROM player p
        JOIN tenant_group_tenants tgt ON tgt.tenant_id = p."tenantId"
        WHERE p."appId" = auth.uid()
          AND p.global_person_id IS NOT NULL
          AND tgt.tenant_group = tenant_group_person_fields.tenant_group
      )
    )
  )
  WITH CHECK (
    tenant_group IN (
      SELECT tgt.tenant_group
      FROM tenant_group_tenants tgt
      JOIN "tenantUsers" tu ON tu."tenantId" = tgt.tenant_id
      WHERE tu."userId" = auth.uid()::text
    )
    AND (
      person_key = 'app:' || auth.uid()::text
      OR person_key IN (
        SELECT 'global:' || p.global_person_id::text
        FROM player p
        JOIN tenant_group_tenants tgt ON tgt.tenant_id = p."tenantId"
        WHERE p."appId" = auth.uid()
          AND p.global_person_id IS NOT NULL
          AND tgt.tenant_group = tenant_group_person_fields.tenant_group
      )
    )
  );

CREATE POLICY "admins_update_tenant_group_person_fields"
  ON tenant_groups FOR UPDATE
  USING (
    id IN (
      SELECT tgt.tenant_group
      FROM tenant_group_tenants tgt
      JOIN "tenantUsers" tu ON tu."tenantId" = tgt.tenant_id
      WHERE tu."userId" = auth.uid()::text AND tu.role = 1
    )
  )
  WITH CHECK (
    id IN (
      SELECT tgt.tenant_group
      FROM tenant_group_tenants tgt
      JOIN "tenantUsers" tu ON tu."tenantId" = tgt.tenant_id
      WHERE tu."userId" = auth.uid()::text AND tu.role = 1
    )
  );